<a href="https://colab.research.google.com/github/1uch0/LLM_Udemy_course/blob/main/MaintenancePrediction_and_MachineSelection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##IMPORT LIBRARIES
import numpy as np # library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices
import matplotlib.pyplot as plt #creating static, animated, and interactive visualizations. It is widely used in data analysis,
import pandas as pd #Python library for data analysis and manipulation. It provides flexible data structures, primarily Series (1D arrays) and DataFrame (2D tables)
import gradio as gr



In [5]:
#IMPORT THE DATASET

dataset = pd.read_csv('synthetic_cnc_machine_data_v3.csv')

print(dataset)
print("----------------Aqui es donde se importa el dataset organizado------------------")

X = dataset.iloc[:, 1:-1].values #Extract all the columns in the datse except the last one
y = dataset.iloc[:, -1].values #Usually in the datasets the last column is the dependet variable, output. In this case we dont want a range. Just the last column
print(X)
print(y)

               Timestamp  Temperature  Energy_Consumed  Vibration_Level  \
0    2025-01-01 00:00:00    74.967142         6.399355         0.432482   
1    2025-01-01 00:05:00    68.617357         5.924634         0.485548   
2    2025-01-01 00:10:00    76.476885         5.059630         0.420758   
3    2025-01-01 00:15:00    85.230299         4.353063         0.469204   
4    2025-01-01 00:20:00    67.658466         5.698223         0.310639   
..                   ...          ...              ...              ...   
995  2025-01-04 10:55:00    67.188997         6.070150         0.507748   
996  2025-01-04 11:00:00    87.976865         4.973479         0.525775   
997  2025-01-04 11:05:00    76.408429         4.118125         0.375824   
998  2025-01-04 11:10:00    64.288210         4.836933         0.533418   
999  2025-01-04 11:15:00    75.725828         4.255097         0.484474   

     Failure_Status  
0                 0  
1                 0  
2                 0  
3          

In [6]:
##Splitting data into test set and training set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


In [7]:
print(X_train)

[[48.76104276  7.15730821  0.53437879]
 [59.9837999   5.35144821  0.40480815]
 [60.33023857  4.37328278  0.57324921]
 ...
 [76.45484181  3.80607499  0.45499871]
 [76.33919022  6.63911681  0.57307641]
 [50.40329876  3.53562512  0.44910364]]


In [8]:
print(X_test)

[[61.3600923   5.95530521  0.62446796]
 [70.82283989  4.78886976  0.53937973]
 [60.14273954  5.24075318  0.49328217]
 [70.97676099  4.55671775  0.38834756]
 [75.04987279  4.41831909  0.69764406]
 [69.34249739  6.95834745  0.59854497]
 [37.5873266   5.53875599  0.62357822]
 [68.13128356  4.51693895  0.48832341]
 [73.24166352  4.3904878   0.44416982]
 [52.36959845  6.38009135  0.51551907]
 [73.66598246  4.47138332  0.52942241]
 [53.92516765  4.84994441  0.51733417]
 [69.59842049  4.80509172  0.31793967]
 [72.32049937  3.51510203  0.60971527]
 [63.18948343  2.05961137  0.4931366 ]
 [74.73592431  5.4535343   0.55918141]
 [68.38714288  6.10818282  0.38105881]
 [85.79212816  5.89519322  0.50012055]
 [77.56988617  4.81710356  0.31234473]
 [59.62753846  7.06150358  0.47210371]
 [62.95656309  5.63472147  0.70122704]
 [54.84808938  4.86598283  0.4214014 ]
 [65.5570674   5.02079371  0.6200079 ]
 [56.01432426  4.18180112  0.46686916]
 [77.17542256  4.41692256  0.48256457]
 [77.51933033  6.0506544 

In [9]:
print(y_test)

[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [10]:
##FEATURE SCALING
#Standarization just for the training part of the data

#JUST APPLY FEAUTURE SCALING TO THE NUMERICAL VALUES, NOT TO THE DUMMY VARIABKLES (CLASSES), just aged and salary

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)


#We need to apply the same transforation in the same scaler to the test set

X_test = sc.transform(X_test)


In [11]:
print(X_train)

[[-2.18226357  2.08868505  0.36512505]
 [-1.03516603  0.2765596  -0.97024331]
 [-0.99975593 -0.70499958  0.76572764]
 ...
 [ 0.64836785 -1.27417529 -0.4529742 ]
 [ 0.6365469   1.56869577  0.76394676]
 [-2.01440573 -1.54556349 -0.51372947]]


In [45]:
print(X_test)

[[-8.94492782e-01  8.82511687e-01  1.29359335e+00]
 [ 7.27111241e-02 -2.87970712e-01  4.16665268e-01]
 [-1.01892053e+00  1.65480518e-01 -5.84209392e-02]
 [ 8.84436670e-02 -5.20928177e-01 -1.13988793e+00]
 [ 5.04763516e-01 -6.59807014e-01  2.04775380e+00]
 [-7.85972606e-02  1.88903399e+00  1.02642834e+00]
 [-3.32434856e+00  4.64517252e-01  1.28442360e+00]
 [-2.02397535e-01 -5.60844990e-01 -1.09526459e-01]
 [ 3.19943299e-01 -6.87734863e-01 -5.64577859e-01]
 [-1.81342681e+00  1.30877163e+00  1.70754824e-01]
 [ 3.63313676e-01 -6.06558675e-01  3.14044130e-01]
 [-1.65442938e+00 -2.26684161e-01  1.89461413e-01]
 [-5.24389145e-02 -2.71692471e-01 -1.86551888e+00]
 [ 2.25789507e-01 -1.56615778e+00  1.14155063e+00]
 [-7.07507531e-01 -3.02669828e+00 -5.99212564e-02]
 [ 4.72674295e-01  3.78999884e-01  6.20743466e-01]
 [-1.76245708e-01  1.03591971e+00 -1.21500649e+00]
 [ 1.60274814e+00  8.22191140e-01  1.20560765e-02]
 [ 7.62338471e-01 -2.59638957e-01 -1.92318092e+00]
 [-1.07158013e+00  1.99254801e+

In [38]:
## Decision_Tree_Classification

In [49]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [50]:
y_pred = classifier.predict(sc.transform([[59.98, 5.35, 0.4]]))
print(y_pred)

[1]


In [51]:
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [57]:
import gradio as gr
import matplotlib.pyplot as plt

# Keep your histories for plotting
temperature_history = []
energy_history = []
vibration_history = []
time_steps = []
counter = 0

def update_plot(temperature, energy_consumed, vibration_level):
    global counter
    counter += 1

    time_steps.append(counter)
    temperature_history.append(temperature)
    energy_history.append(energy_consumed)
    vibration_history.append(vibration_level)

    plt.figure(figsize=(8, 4))
    plt.plot(time_steps, temperature_history, label="Temperature (°C)", color='r')
    plt.plot(time_steps, energy_history, label="Energy Consumed (kWh)", color='g')
    plt.plot(time_steps, vibration_history, label="Vibration Level", color='b')
    plt.xlabel("Time Step")
    plt.ylabel("Value")
    plt.title("Machine Parameters Over Time")
    plt.legend()
    plt.tight_layout()
    return plt

def predict_failure(temperature, energy_consumed, vibration_level):
    y_pred = classifier.predict(sc.transform([[temperature, energy_consumed, vibration_level]]))
    return "⚠️ Machine is FAILING!" if y_pred[0] == 1 else "✅ Machine is OK."

# Simple "machine scoring" for altruistic collaboration
def evaluate_machine(temp, energy, vibration, load, wear, availability):
    # This is just an example score function → you can replace with your own logic
    health = max(0, 100 - (load + wear*50 + vibration*100)) * availability
    return f"Score: {round(health,2)}"

with gr.Blocks() as demo:
    gr.Markdown("## 🏭 Machine Monitoring & Altruistic Collaboration")

    with gr.Tabs():
        # -------- Tab 1: Single machine --------
        with gr.Tab("Single Machine"):
            gr.Markdown("### Machine Parameters")

            with gr.Row():
                temp = gr.Slider(0, 100, 59.98, step=1, label="Temperature (°C)")
                energy = gr.Slider(0, 10, 5.35, step=0.1, label="Energy Consumed (kWh)")
                vibration = gr.Slider(0, 1, 0.4, step=0.01, label="Vibration Level")

            with gr.Row():
                tool_load = gr.Slider(0, 100, 30, step=1, label="Tool Load (%)")
                tool_wear = gr.Slider(0, 1, 0.2, step=0.01, label="Tool Wear (0-1)")
                availability = gr.Slider(0, 1, 0.9, step=0.01, label="Availability")

            plot_output = gr.Plot()
            status_output = gr.Textbox(label="Machine Status", interactive=False)
            score_output = gr.Textbox(label="Altruistic Collaboration Score", interactive=False)

            # Live plot updates
            temp.change(update_plot, [temp, energy, vibration], plot_output)
            energy.change(update_plot, [temp, energy, vibration], plot_output)
            vibration.change(update_plot, [temp, energy, vibration], plot_output)

            # Prediction button
            predict_btn = gr.Button("Predict Machine Failure")
            predict_btn.click(predict_failure, [temp, energy, vibration], status_output)

            # Collaboration score
            collab_btn = gr.Button("Evaluate Machine Collaboration Potential")
            collab_btn.click(evaluate_machine, [temp, energy, vibration, tool_load, tool_wear, availability], score_output)

        # -------- Tab 2: Compare 4 machines --------
        with gr.Tab("Compare 4 Machines"):
            gr.Markdown("### Multi-Machine Comparison for Altruistic Collaboration")

            machines = []
            for i in range(1,5):
                with gr.Column():
                    gr.Markdown(f"**Machine {i}**")
                    t = gr.Slider(0, 100, 50, step=1, label=f"M{i} Temperature (°C)")
                    e = gr.Slider(0, 10, 5, step=0.1, label=f"M{i} Energy (kWh)")
                    v = gr.Slider(0, 1, 0.3, step=0.01, label=f"M{i} Vibration")
                    l = gr.Slider(0, 100, 30, step=1, label=f"M{i} Tool Load (%)")
                    w = gr.Slider(0, 1, 0.2, step=0.01, label=f"M{i} Tool Wear (0-1)")
                    a = gr.Slider(0, 1, 0.9, step=0.01, label=f"M{i} Availability")
                    score_box = gr.Textbox(label=f"M{i} Score", interactive=False)
                    machines.append(((t,e,v,l,w,a), score_box))

            # One button to evaluate all 4 machines
            compare_btn = gr.Button("Evaluate All Machines")
            for (inputs, out) in machines:
                compare_btn.click(evaluate_machine, list(inputs), out)

demo.launch()


It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://4d352c85b0e25a3295.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[170   0]
 [ 30   0]]


0.85

In [22]:
## RANDOM FOREST

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0) #10 estimators or 10ntrees on the forest
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(y_pred)


## Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

In [48]:
##SVM

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
[[170   0]
 [ 30   0]]


0.85